--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ElectroGamesYT/SimpleHeal-Pocketmine
build-by-default: true
branches:
- master
projects:
  SimpleHeal-Pocketmine:
    path: "heart"
...
