---
name: SimpleHeal
api: 3.0.0
version: 1.0.0
main: Electro\SimpleHeal\Main
author: Electro
description: Heals yourslef to max health

commands:
 heal:
  description: Heal yourslef to max health
  permission: simpleheal.use
permissions:
  simpleheal.use:
    description: Permission to heal yourself
    default: op
...
