---
name: SimpleHeal
api: 3.22.1
version: 1.0.0
main: Electro\SimpleHeal\Main
author: Electro
description: §eMenyembuhkan diri sendiri atau orang lain untuk kesehatan maksimal

commands:
 heal:
  description: §eMenyembuhkan diri sendiri atau orang lain untuk kesehatan maksimal
  permission: simpleheal.use
permissions:
  simpleheal.use:
    description: Izin untuk menyembuhkan diri sendiri atau orang lain
    default: op
...
