---
name: SimpleHeal
api: [3.0.0, 4.0.0]
version: 1.0.0
main: Electro\SimpleHeal\Main
author: Electro
description: Healing Plugin

commands:
 heal:
  description: Heal yourslef to max health
  permission: heal.use
permissions:
  heal.use:
    description: Permission to heal yourself
    default: op
...
